server:
  port: 8901

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - hystrix.stream

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 3000
      circuitBreaker:
        requestVolumeThreshold: 20
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 5000
      metrics:
        rollingStats:
          timeInMilliseconds: 10000
  threadpool:
    default:
      coreSize: 10
      maxQueueSize: 200
      queueSizeRejectionThreshold: 5

ribbon:
  ReadTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
